server:
  port: ${PORT:8888}
  
spring:
  application:
    name: dummy-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmanKishan/dummy-configuration
          searchPaths: configuration

logging:
  level:
    com.dummy.configserver: DEBUG